### PR TITLE
Polymaker Polyflex material correction/update

### PR DESCRIPTION
**Pull request by 64bittuning**
Polymaker still makes the PolyFlex materials, however they are not a PLA based material, they are TPU.
Please see the following link to their site.

https://us.polymaker.com/search?type=product&options%5Bprefix%5D=last&options%5Bunavailable_products%5D=last&q=polyflex

### CODE REVIEW

**Comment by 64bittuning** [comment]
Additionally, referring to https://github.com/Ultimaker/Cura/issues/11381 
I found that the "+" in the materials field was causing the materials to not load a profile, even when expressly names in a profile set that I was creating. Simply changing the <material> back to a standard type, and then editing the label seemed to correct the issue.
image
As you can see in the above screenclip, selecting materials with a non-standard name will cause an error to report, and remove all profile options. 

This PR will correct the issue and allow these filaments to be used based off a profile that either attributes to a "generic_" profile, or when called specifically in a "Quality" file that is specific to a machine or machine family.

**Comment by Ghostkeeper** [comment]
Perhaps a better solution, looking to the future, is to change Cura/Uranium such that these are working properly? A lot of people made their own materials too, and those wouldn't be fixed by this change. This change also has the danger that it causes the PLA profiles to be applied to PLA+ materials, which may clash (if a printer has both). They had a different material type for a reason.

**Comment by 64bittuning** [comment]
Having the + in the material name, causes a hard fault, and Cura cannot and does not understand it.

I would have posted this as a bug report but that is unfortunately not available here.

Perhaps a release to the fdm_matetials repository with a list of "accepted" materials categories would be a good idea. I believe if you look deeper into this, you might find that the + is the source of the issue and should just be replaced by "plus".

I stand by this PR as I have done a lot of checking with ways to fix it.

**Comment by Ghostkeeper** [comment]
Yeah, what I was saying is that perhaps this should be fixed from Cura's side, to allow Cura to understand the `+`.

Changing the `+` into the word `plus` would be better as a workaround because it would keep the PLA+ profiles as a separate group of profiles from PLA. Both solutions would require a version upgrade to update the user's existing profiles though. I'd rather fix this from Cura's side instead.

**Comment by 64bittuning** [comment]
Thank you for the heads explanation, I understand now.

**Pull request closed without merging**
