### PR TITLE
CS-676 XSD template input validation for brand, material and color

### PR DESCRIPTION
**Pull request by xli12**
Input validation for brand, material and color. 2 <= length <= 100 characters.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Some context: we found this in the Marketplace API when people were uploading XML files with invalid values. Maybe @nallath and @robinmdh want to have a look?

**Comment by nallath** [comment]
I don't think Cura puts a limit on this. I guess we should also put a limit on the Cura interface then?

Is there a specific reason why we want the limit at all?

**Comment by ChrisTerBeke** [comment]
These are based on the existing limits in our back-end models, which are needed for properly displaying these fields in the user interfaces (without weird overflows/newlines/etc).

**Comment by Ghostkeeper** [comment]
IIRC we had a brand with just one letter, didn't we? I remember Mariska talking about how the contribution portal was blocking that at some point.

**Comment by ChrisTerBeke** [comment]
@Ghostkeeper yes, it was then decided the minimum number of characters for a brand is 2, and that the portal whould show the correct error if an XML is uploaded that does not have this requirement. The changes to the XSD we made for that on our side are reflected in this PR.

**Pull request merged**
