### PR TITLE
Update imade3d jellyboxes' materials

### PR DESCRIPTION
**Pull request by filipgoc**
This pull request updates materials for IMADE3D JellyBOX printers. It does not affect any other printer. This request is submitted in conjunction with a similarly named one in the cura repository.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
(Developers, see ticket CURA-6586.)

Merge together with https://github.com/Ultimaker/Cura/pull/5905.

**Comment by filipgoc** [comment]
I reviewed the conflict. It's easily resolvable - everything related to imade3d JellyBOX should be deleted (just one <machine></machine> tag). Everything else should stay.

I don't have write permissions, so I'm leaving this to the kind maintainers.

**Comment by filipgoc** [comment]
As I was instructed to resolve a related commit in the Cura repo, I gave this the same treatment. I merged the latest 4.2 master into this branch and resolved the conflicts (everything coming from 4.2 for 3rd party files accepted). It should be merge-able now. If it makes things more complicated for you and not less, feel free to reset back. Cheers.

**Comment by nallath** [comment]
I'm still getting warnings/errors :(

```
2019-07-17 13:00:18,427 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material generic_pla #2_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,428 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_green_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,430 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material generic_pla_175_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,432 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_magenta_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,433 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material tizyx_petg_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,438 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_red_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,438 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material generic_pla_175 #2_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,438 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_blue_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,439 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_black_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,440 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material tizyx_flex_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,440 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material custom_material_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,441 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_silver-metallic_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,442 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material tizyx_pla_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,445 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_yellow_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,445 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_transparent_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,447 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_pearl-white_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,448 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material generic_pla_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,449 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_orange_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,450 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material tizyx_pla_bois_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,453 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material ultimaker_pla_white_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,454 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material tizyx_pva_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
2019-07-17 13:00:18,455 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material generic_petg_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
```

**Comment by filipgoc** [comment]
Grrr. Ok. I'll give it another go. I presume you're merging into the latest master. If not, please speak up.

**Comment by nallath** [comment]
Yup. Merged both pull requests into master and got the errors i posted.

**Comment by filipgoc** [comment]
@nallath Thanks so much for posting the error. I could not have figured it out without - I don't get the errors locally as these materials affected are actually hidden in the interface using the definition file.

There used to be imade3d_jellybox_0.4_2-fans.inst.cfg variant, which I deleted coinciding with these changes in materials. Both commits have to go through (Cura and fdm repos) for this to work.

I have fixed the reference to a deleted variant in all the files but one. 

**This one is NOT fixed**

❓ Isn't `custom_material` something that a user would create? Where can I change this? I searched the whole repo for a trace of   `hotend id="0.4 mm 2-fans"` and I did not find anything. 🤔 

- [ ] custom_material_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.

**These are now fixed** 

- [x] generic_petg_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] generic_pla #2_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] generic_pla_175 #2_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] generic_pla_175_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] generic_pla_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] tizyx_flex_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] tizyx_petg_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] tizyx_pla_bois_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] tizyx_pla_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] tizyx_pva_imade3d_jellybox_0.4_mm_2-fans    contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_black_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_blue_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_green_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_magenta_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_orange_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_pearl-white_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_red_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_silver-metallic_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_transparent_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_white_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.
- [x] ultimaker_pla_yellow_imade3d_jellybox_0.4_mm_2-fans contains a variant 0.4 mm 2-fans that does not exist. It will not be added into the material lookup tree.

**Pull request merged**
