### PR TITLE
added empty material and changed colors for all generic materials

### PR DESCRIPTION
**Pull request by maukcc**
Red         Nylon
pink         CPE
purple      CPE+
blue         PC
light blue  PETG
green       PLA
yellow      PVA
brown      HIPS
grey         ABS
black        TPU
background color  EMPTY

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Not sure I agree with both of these changes. Why would we want an "empty" material? For when you're printing air?

And these colour changes are quite unnecessary too. They change every colour to a pure colour and that's at odds with what our UX designers chose.

**Comment by maukcc** [comment]
The empty material is for

- the user will have empty materials when 1st starting the program. It will add to the experience of setting up their printer

- if there are multiple extruders then the unused extruders should be filled with this empty material (preferably automatically) as it will else influence things like bed temperature

**Comment by Ghostkeeper** [comment]
The first issue is typically done by selecting PLA by default. If you were to select "No material" the user would have to select a material before being able to slice or print and that is a bad workflow.

The second issue can be resolved more inherently by changing how the resolve function selects which extruders to use.

**Comment by maukcc** [comment]
I would like a 1st startup workflow to go like:
1 select printer
2 select nozzles
3 select materials for nozzles
with separate pop-ups, but that is personal preference so strike that :)

the second issue I will present over at the Cura repository.

And this can be closed then.

**Comment by BagelOrb** [comment]
I don't agree that having an empty material by default is bad workflow.
When you start Cura the first time it also doesn't assume which printer you use, so why should it assume which material you have loaded?

I think it's good to be forced to choose which material is in the printer, but perhaps this should be part of the add machine wizard...?

**Comment by daid** [comment]
@BagelOrb however, having an empty material does not match the design intent, the material profiles describe a material, not a machine state. We have a clear definition of a "no material" state in the UM3. Adding a profile like this just fucks that up.

**Comment by BagelOrb** [comment]
Good point.

**Comment by maukcc** [comment]
Can we envoke that "no material" state in the definitions files for 1st start? And choose that state somehow in the progam at materials.

**Pull request closed without merging**
