### PR TITLE
Cartesio updates

### PR DESCRIPTION
**Pull request by maukcc**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Devs, see CURA-3683.

**Comment by nallath** [comment]
Either this or the linked request breaks it. It makes it impossible for me to add a cartisio printer.

**Comment by maukcc** [comment]
Is there anything I can help with, as I am not familiar with CURA-3683

**Comment by nallath** [comment]
Cura 3683 is our way of tracking that we need to do something. As far as I could see, either this pull or the FDM pull request that you made seems to have broken the ability to add the Cartiso. 

But I made a boo-boo myself. Sorry about that. Another pull request broke it (which has been resolved now), so yours can go ahead.

**Pull request merged**
