### PR TITLE
Support for Tronxy machines

### PR DESCRIPTION
**Pull request by 64bittuning**
Updated generic filaments with some good starting points for the most common materials used.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Merge together with https://github.com/Ultimaker/Cura/pull/7553.

**Comment by 64bittuning** [comment]
I had these files placed in that PR originally, and I was told to put them here.

**Comment by Ghostkeeper** [comment]
Yes that's correct, sorry. What I said earlier was just an instruction towards the developers. We'll need to merge these at the same time.

**Comment by 64bittuning** [comment]
An error occurred and this repo was deleted. Re-opened as #130

**Pull request closed without merging**
