### PR TITLE
Change package name from fdm_materials to fdm-materials

### PR DESCRIPTION
**Pull request by alexborro**
I think this fix the package name issue, but I don't know how you guys are used to generate the package. I tried locally and seems to work. Please test with your current workflow.

The debian package name should now be: `fdm-materials-<version>-Linux.deb`
If you run the command: `dpkg-deb -I fdm-materials-<version>-Linux.deb`
you should have an output with following line: `Package: fdm-materials`

### CODE REVIEW

**Comment by nallath** [comment]
This would break the Cura builds, since they also depend on this.

**Comment by Ghostkeeper** [comment]
Doesn't Debian support underscores in the package names then? What is the issue this is trying to fix?

**Comment by atrebelo** [comment]
@alexborro @nallath @jackha @bryanfoley This needs to be discussed as it will have an impact on Cura, but it is needed on our side in order to use the new build system for the firmware. Can we discuss IRL please?

**Comment by rburema** [comment]
As discussed with the rest of the Cura team, I just made a build with this branch. It seems no changes are required on our side.

I've put 'our' ticket for this through to QA as this is not blocking us as far as I can see (that is to say: go ahead if you're ready).

:-)

**Pull request merged**
