### PR TITLE
Kati hal arge printers (alya, alya nx, kupido)

### PR DESCRIPTION
**Pull request by nbennett1978**
Hi,
i embedded settings for our printers (Alya 3DP, Alya NX 3DP, KUPIDO ), as proposed upon my last pull request, in the material profiles for generic PLA and generic ABS.
Please let me know if this is streamlined with your current design goals-

Nureddin Bennett

### CODE REVIEW

**Comment by nbennett1978** [comment]
Hi,
İ revised the definitions of kupido and alya3dp printers, and added alyanx3dp, an extended version of alya3dp, in a different pull request in parallel. Unfortunately the pull request hasn’t been looked at again, after I implemented the requested changes

**Comment by nbennett1978** [comment]
Thank you very much for the help- I will keep it in mind for the future

**Comment by Ghostkeeper** [comment]
Ah, so we should check this together with https://github.com/Ultimaker/Cura/pull/5179.

**Comment by nbennett1978** [comment]
That, of course, would be great 👍😀

**Comment by Ghostkeeper** [comment]
(Waiting on changes requested in Ultimaker/Cura#5179.)

**Pull request merged**
