### PR TITLE
Add PAHTCF15/PC/PETCF15/PPGF30

### PR DESCRIPTION
**Pull request by heed818**
Adding printer da Vinci Pro EVO

### CODE REVIEW

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,do you think these request could able merge to version 5.1 ?
Thanks.

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,do you think these request could able merge to version 5.1 ?
Thanks.

**Comment by heed818** [comment]
Hi Sir @jellespijker, due to our new machine da Vinci EVO has been merged, could our new materials been merged,too?
Thanks.

**Comment by heed818** [comment]
Hi Sir @rburema @robinmdh @jellespijker  ,
due to our new machine da Vinci EVO has been merged, could our new materials been merged,too?
including PAHT CF15/PC/PET CF15/PP GF30
Thanks.

**Comment by rburema** [comment]
Hi @heed818 could you please link the PR's together next time? Then we know they should be reviewed together.

**Comment by heed818** [comment]
> Hi @heed818 could you please link the PR's together next time? Then we know they should be reviewed together.

Hi @rburema ,what dose "PR" mean?  Thanks.

**Comment by rburema** [comment]
@heed818 'P.R.' in this context means 'Pull Request'.

**Pull request merged**
