### PR TITLE
add creawsomemod settings

### PR DESCRIPTION
**Pull request by trouch**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-6554. This belongs together with https://github.com/Ultimaker/Cura/pull/5809.

**Comment by nallath** [comment]
You can make these profiles a lot shorter.
This: 
`
        <machine>
            <machine_identifier manufacturer="Creality3D" product="creawsome_cr10" />
            <setting key="print cooling">0</setting>
            <setting key="standby temperature">200</setting>
            <setting key="retraction speed">45</setting>
            <setting key="retraction amount">5</setting>
            <setting key="print temperature">240</setting>
            <setting key="heated bed temperature">80</setting>
        </machine>

        <machine>
            <machine_identifier manufacturer="Creality3D" product="creawsome_cr10s" />
            <setting key="print cooling">0</setting>
            <setting key="standby temperature">200</setting>
            <setting key="retraction speed">45</setting>
            <setting key="retraction amount">5</setting>
            <setting key="print temperature">240</setting>
            <setting key="heated bed temperature">80</setting>
        </machine>
`
Has the same result as
`
        <machine>
            <machine_identifier manufacturer="Creality3D" product="creawsome_cr10" />
            <machine_identifier manufacturer="Creality3D" product="creawsome_cr10s" />
            <setting key="print cooling">0</setting>
            <setting key="standby temperature">200</setting>
            <setting key="retraction speed">45</setting>
            <setting key="retraction amount">5</setting>
            <setting key="print temperature">240</setting>
            <setting key="heated bed temperature">80</setting>
        </machine>
`

**Comment by trouch** [comment]
thanks @nallath for the recommendation, I fixed that.

**Comment by Ghostkeeper** [comment]
No specific settings here for TPU? Is that an oversight or was that on purpose?

**Comment by trouch** [comment]
> No specific settings here for TPU? Is that an oversight or was that on purpose?

I hadn't time to properly test different TPU filament, but looks people using such material already knows settings to use. Low priority. 

I've got request to add PVA/Nylon/PC... actually full range of material I can't test so I'd rather prefer to avoid providing bad settings. I hope some other people will add qualities required later based on the existing work.

**Pull request merged**
