### PR TITLE
EM-1662 materials

### PR DESCRIPTION
**Pull request by MarcoTvM**

### CODE REVIEW

**Comment by nallath** [comment]
Huh? 260 is something that -all- our printers can reach. So why the hell are we saying that the default is incompatible?

**Comment by ckielstra** [comment]
@nallath 'unknown' is a valid defined setting in the specification but was rejected in both UM3 and Cura. This has now been fixed in this issue.

The other issue about disabling the materials by default because of a too high temperature is wrong. Long time ago someone made a copy/paste error. This should be fixed but is a new, separate, issue. Only, what project to report the new issue on? Who manages this materials repository?

**Comment by nallath** [comment]
We should fix the real problem; The software not adhering to the spec. These changes simply hide the problem. 

I don't know what copy paste error you refer to. As far as I see, we should have all materials enabled by default. It's up to machines (or machine families) to disable them.

**Comment by oliv3r** [comment]
mental note: if/when merging this, squash the commits :)

**Comment by ckielstra** [comment]
@oliv3r Too late, 4 comments up the branch was already merged and deleted.

**Comment by Ghostkeeper** [comment]
Previously "unknown" was not a known keyword and therefore interpreted as "no" for safety.

Since I made the changes requested by CKielstra, Cura now interprets the state "unknown" as being "yes" instead of "no". And then proceeds to show the material as being Not Supported if there are no valid profiles for it. So this sort of adheres to the spec, except that Cura has additional data, which materials we have profiles for, and views this as leading instead of the tag in the material profile.

**Comment by Ghostkeeper** [comment]
The copy-paste error CKielstra was referring to was only the case for TPU. Basically, it was probably copied from CPE+ back when we created the material profile. And CPE+ had the tag that it needs to be too hot for most printers, so TPU had it too even though it was only printed at 228 degrees C.

I've just removed that tag for TPU. The tag still exists for CPE+ and PC. Should we keep it there? I'm inclined to allow third-party printers to print with it by default and leave the responsibility to block it with the designer of the printer definition rather than with us.

**Pull request merged**
