### PR TITLE
Created material profiles for Eryone PLA, PLA Wood, PLA Matte and PETG 

### PR DESCRIPTION
**Pull request by dapostol73**

### CODE REVIEW

**Comment by dapostol73** [comment]
Can anyone tell me if their is a process for getting these materials reviewed and merged?

**Comment by nallath** [comment]
There is a process, we're just a bit behind on checking things, sorry.

Is there a specific reason that you changed the material types of these materials? For machines that have quality profiles per material, the "weird" types that you used (eg "pla-glow") will result in "not supported" messages in cura.

**Comment by dapostol73** [comment]
Hi Nallath, thanks for the response.  As this is my first add to the system, I was following what other materials have done when creating them, like Velleman where they have these Types.  Happy to learn what the proper setup is and set to PLA, is there any documentation for material settings.

image

**Comment by nallath** [comment]
The system is explained a bit more in https://github.com/Ultimaker/Cura/wiki/Profiles-&-Settings

So basicly, the <material> tag is used to check what quality profile is being used. If you use "pla-wood" it will not be able to find a quality profile for it. It will work, but it will mean that most printers don't have a profile for it. Since I assume that PLA wood is pretty close to pla, it's probably best to keep it's type the same (and so it will use the basic quality of normal PLA)

**Comment by dapostol73** [comment]
Thanks for the info and feedback, this helps.   On my last submit I remove the any Type with "PLA-SubType" and set them to "PLA" leaving only the label to have "PLA SubType"

**Comment by dapostol73** [comment]
Hello, is there anything other feedback on this pull request or something I need to do to get this merge into the master?

Thanks,

**Comment by konskarm** [comment]
Hi @dapostol73. We haven't started re-reviewing this PR yet. Sometimes due to our workload it takes time to pick up and review pull requests. We will let you know if anything else is needed once we get to it.

**Review by Ghostkeeper — APPROVED** [review]

**Pull request merged**
