### PR TITLE
color changes for petg and hips

### PR DESCRIPTION
**Pull request by maukcc**

### CODE REVIEW

**Comment by BagelOrb** [comment]
Why did you want different colours?

Op 9 mrt. 2017 08:57 schreef "MaukCC" <notifications@github.com>:

**Comment by maukcc** [comment]
Because we can :)
and because we then can see at a glance if we have different materials selected for different nozzles, resulting in unwanted bed temperatures.
example:
I made a previous print with PLA and PETG and the print I want to do now only needs PLA. I can then see that my 2nd extruder still has a different color, and therefore the bed might not have the correct temp.

preferably we want the program to start with empty materials pre-selected for all extruders except extruder_0. And give those unselected extruders a black color. 
I will make a material that has a name called "empty". 
Is there a way in definitions or variants or extruders to always let the program start with that material?

**Comment by BagelOrb** [comment]
Ah, so the colors of HIPS and PETG were too much alike.

Sounds like this is something we would want to merge.

**Comment by BagelOrb** [comment]
The new colors are quite saturated comapred to existing colors.... Just an obervation.

Also PU and ABS have very similar colors

**Comment by Ghostkeeper** [comment]
The old colour was simply copied from PLA. We should change them to differentiate between the materials.

**Comment by Ghostkeeper** [comment]
The new colours are saturated, but we have very saturated colours for other materials as well, such as PLA and PVA. I don't think that's a problem.

PETG now is orange-yellow, which is a very similar colour to PLA (but slightly darker). Not ideal. But it's fine for now.

**Pull request merged**
