### PR TITLE
Misp 1335 new petg profiles

### PR DESCRIPTION
**Pull request by rijkvanmanen**

### CODE REVIEW

**Comment by suppomi** [comment]
CI/CD Validate issue will be solved when PR #161 were merged (otherwise, you can cherry pick 62aed40).

**Comment by rijkvanmanen** [comment]
bumping version numbers was not needed for PETG. Timon did that already...

**Comment by nallath** [comment]
I will cherrypick these changes into 4.9. This branch was based from a too late version of master (so changing the base right now would also move a bunch of things from master to 4.9)

**Review by jbatong — APPROVED** [review]

**Review by shanx — APPROVED** [review]
lgtm

**Review by bryanfoley — APPROVED** [review]

**Pull request merged**
