### PR TITLE
Update Vertex_Delta_ABS.xml.fdm_material

### PR DESCRIPTION
**Pull request by maukcc**
perhaps it is a good idea that new materials from external vendors have no machine section in the files unless specifically asked for by the machine vendor.
Maybe a read.me file would be in order with some guidelines?

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I don't really agree. A material vendor should be able to publish whatever settings they want. The printer vendor doesn't have a final say in what settings to use.

If you claim it doesn't print well, perhaps you can improve the settings instead?

**Comment by maukcc** [comment]
wow, that was closed rather quick.

We agree that a material vendor can publish any setting they want.
We as machine vendor can then say that we chose not to use that material on our machines. 
There was a reason for having machine specific materials.

So, yes the material vendor can publish global settings, no they can not add machine specific settings.
Please reopen these pull requests.

**Comment by maukcc** [comment]
The standard operating procedure would be for the material vendor to send the machine vendor the materials. Ask the machine vendor to:

- test the materials
- publish the machine specific settings.

**Comment by maukcc** [comment]
But in no way they should be allowed to publish machine specific settings without the explicit agreement of the applicable machine vendor.

**Comment by Ghostkeeper** [comment]
> But in no way should the material vendor be allowed to publish machine specific settings without the explicit agreement of the applicable machine vendor.

This is not true. The material vendor can put their material profiles for Cartesio printers on Reddit and you can not prevent him from doing that. You can try to send cease and desist letters to Reddit but that's not going to do anything because these profiles are public domain. Similarly, the material vendor can publish their material profiles for Cartesio printers on Cura and you can't prevent him.

From our point of view it's two parties disagreeing on what should be the optimal settings for this material on that printer. Since I believe that Nuyttens did test the material and you didn't, I'm now siding with him.

But I still hope that you two can come to an agreement on this. @velbn are you reading this?

**Comment by maukcc** [comment]
How come these materials do not show up in Ultimaker printers ?
In other words: how can I prevent them from showing up in our machines?

**Comment by Ghostkeeper** [comment]
They don't show up because they are 1.75mm diameter and Ultimaker printers only support 2.85mm diameter materials.

**Comment by maukcc** [comment]
Ahh 1.75  :)

@velbn Could you please delete the specific settings for the Cartesio machines from your materials? As there are no quality files for them, it will generate errors.

@Ghostkeeper It should be a matter of principle though that there are some guidelines to posting new materials, especially for machine specific settings.  I am sure that this particular one was nothing more then a bad copy/paste routine. Hense my request for a read.me with some guidelines.
I am sure Ultimaker would not be happy if all of a sudden 20 new , untested, materials were added to their machines.

A possible 1st draft for the read.me file:
Thank you for posting or editing new materials.
If adding machine specific settings, they must be tested on the specific machine, or get agreement of the applicable machine vendor.
If machine vendors are not happy with machine specific setting, do not post a new issue, but contact the material vendor for proper values or deleting.

**Comment by Ghostkeeper** [comment]
There is already the HIPS material and I'm planning to post up actual C8 quality profiles next week for one of Ultimaker's printers.

I'm all for creating a CONTRIBUTING file. We should use those more often :(

Not so happy with the requirement to get permission from the 3D printer manufacturer before posting a profile though. In addition to what I said before, that's just not very open. In fact, it essentially requires 3rd party contributors to go through you as well before making any changes (and maybe the nozzle manufacturer too?). Cura would not have had all of its definitions if it weren't for 3rd party contributors.

Besides, we're not asking you for permission either when we change one of the defaults in Cura.

**Comment by velbn** [comment]
@maukcc @Ghostkeeper Sorry for the mix-up. We never intended to put your machine in our settings. This is our fault, not sure how it got there actually.

My Apologies,
Velbn

**Comment by Ghostkeeper** [comment]
Then it seems that MaukCC was right here:

>  I am sure that this particular one was nothing more then a bad copy/paste routine.

I'll reopen these PRs and get them in for the next release. Yeah, sorry for the politics.

**Comment by maukcc** [comment]
@velbn No problem.

@Ghostkeeper I love the politics :) , and I see what you mean. I am just afraid that this level of openness can potentially be mis-used.
Is it possible that when machine specific settings are changed in a PR, the responsible machine vendor gets a notification of the PR? (Jenkins)
If you could remove it that would be appreciated. Should you take out the Ultimaker data as well, as it is just taking up space?

**Comment by nallath** [comment]
The file are also data files, so you can't even exercise copyright on them. So even if these files were not open, a vendor can't prevent anyone from distributing profiles.

**Comment by Ghostkeeper** [comment]
> Should you take out the Ultimaker data as well, as it is just taking up space?

I don't mind it taking up space and I'm sure that our users won't mind the 1kB extra over the 100MB installation that Cura already is. But if it has never been tested and is simply a copy-paste error then we should take it out.

**Comment by Ghostkeeper** [comment]
I've removed specialisation for Cartesio and Ultimaker printers from these four materials: https://github.com/Ultimaker/fdm_materials/commit/eb62b06560d084c02aaebdb15cb1bbc2933fbbfa

**Pull request closed without merging**
