### PR TITLE
EmotionTech materials updated

### PR DESCRIPTION
**Pull request by NicolasBOYARD**
PA6CF and PA6GF added to eMotionTech materials
PA10XX removed from eMotionTech materials
COPA temperature updated
In each resulting material .xml.fdm_material file, IDEX420 Printers machine added

### CODE REVIEW

**Comment by nallath** [comment]
Removing profiles will cause issues without an upgrade script in Cura. If project files still use them, they will become corrupted. As such, please create an accompanying PR that solves that (or simply don't remove the material).

Is there a specific reason that you've removed these profiles?

**Comment by NicolasBOYARD** [comment]
Hello nallath, sorry, I didn't answer this ask. Yes, we removed these 3 materials because they were added in expecting of sells but we never sold it. So, instead of polluting Cura files with useless files, we prefer to remove them.

**Comment by Joeydelarago** [comment]
Hey @NicolasBOYARD, as nallath mentioned we can't remove materials without an upgrade script (unimplemented). So I suggest you add the files back and put a xml comment at the top of the file saying they are deprecated.

**Comment by saumyaj3** [comment]
Hey @NicolasBOYARD!
As @nallath and @Joeydelarago mentioned above, The Cura upgrade script won't work if we delete the materials. Can you please put them back so that the printer definitions PR: https://github.com/Ultimaker/Cura/pull/15101 could be updated? @Joeydelarago suggestion could be helpful.

**Comment by NicolasBOYARD** [comment]
Hi @saumyaj3 , Sorry, I re-read every comments on this conversation : files of the 3 deprecated materials are back with "deprecated" in the name and set to "non compatible" with the printers.
Linter has been successfully checked

**Comment by saumyaj3** [comment]
> Hi @saumyaj3 , Sorry, I re-read every comments on this conversation : files of the 3 deprecated materials are back with "deprecated" in the name and set to "non compatible" with the printers. Linter has been successfully checked

Hey! I see another PR open https://github.com/Ultimaker/fdm_materials/pull/249 with the said changes. I'll close this one.

**Pull request closed without merging**
