### PR TITLE
First_eMotionTech_Material_Pull

### PR DESCRIPTION
**Pull request by KOUBeMT**
Hello,
Adding some materials for eMotionTech's printers (specially Strateo3D)
Thanks

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Have you got any technical data sheet on these filaments?

You made a commit to fix indentation, but these files have mixed indentation styles: tabs and spaces. A heinous crime! Our [code conventions](https://github.com/Ultimaker/Meta/blob/master/general/generic_code_conventions.md) specify using 4 spaces per indentation.

**Comment by Ghostkeeper** [comment]
Belongs to this PR: https://github.com/Ultimaker/Cura/pull/5855
They should be merged together.

**Comment by Ghostkeeper** [comment]
Developers, please see CURA-6570.

**Comment by KOUBeMT** [comment]
Hello,
Are you sure there is still indentation issues. can you show me were? i thought i fixed them all.... :)

**Comment by Ghostkeeper** [comment]
That latest commit fixed them all :)

**Comment by nallath** [comment]
I'm getting a bunch of errors when I merge this: 
`2019-07-01 11:36:42,483 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pla_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,484 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pla_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,484 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pla_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,486 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_petg_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,486 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_petg_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,486 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_petg_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,488 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-oks_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,488 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-oks_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,489 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-oks_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,491 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-m_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,492 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-m_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,493 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-m_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,497 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_tpu98a_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,497 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_tpu98a_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,498 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_tpu98a_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,500 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-s_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,501 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-s_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,501 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_pva-s_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,503 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_abs_strateo3d_Standard_0.8 contains a variant Standard 0.8 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,503 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_abs_strateo3d_Standard_1.0 contains a variant Standard 1.0 that does not exist. It will not be added into the material lookup tree.
2019-07-01 11:36:42,503 - ERROR - [MainThread] cura.Machines.MaterialManager.__addMaterialMetadataIntoLookupTree [266]: Material emotiontech_abs_strateo3d_Standard_1.2 contains a variant Standard 1.2 that does not exist. It will not be added into the material lookup tree.
`

**Comment by diegopradogesto** [comment]
Hi @KOUBeMT , we found out that in the materials that you added there are some variants that don't exist in Cura, therefore we get a lot of error messages in the logs.

Could you please take a look at it. Otherwise we can't accept these changes.

**Comment by KOUBeMT** [comment]
Please check last commit, it should resolve the problem...
I put all the variants that are not yet supported / commit-ed in comment, we are still working/optimizing printing profiles for those variants they should be out soon :)

**Pull request merged**
