### PR TITLE
Add Velleman Profiles

### PR DESCRIPTION
**Pull request by velbn**
Hi
We've added our PLA,ABS,PET and TPU filaments

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-4819

**Comment by alekseisasin** [comment]
@velbn , can your format definition files, insert 4 spaces instead of 2.

**Comment by velbn** [comment]
Done

**Comment by alekseisasin** [comment]
@velbn Thank you, looks good. During adding your profile we found that cura for some reason has difficulties adding different materials. We work on this now and as soon we solve the issue we will merge your changed also.

**Pull request merged**
