### PR TITLE
Improve material validation script

### PR DESCRIPTION
**Pull request by nallath**
As the name suggests. I've added an XSD that validates if a material profile is correct.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Not sure why the build is failing in this repo. In the cloud service we use the same validation file and it works fine there.

**Comment by LipuFei** [comment]
@nallath We don't have `lxml` on the CI machines :(

**Comment by ChrisTerBeke** [comment]
Then this 'ci' is pretty pointless, as it won't prevent pushing incorrect configs to master/releases.

**Comment by LipuFei** [comment]
https://github.com/Ultimaker/cura-build-environment/pull/53

**Comment by LipuFei** [comment]
@nallath I've backed up your script and restored the old.

**Comment by ChrisTerBeke** [comment]
Are we going to add the validation script back or not?

**Comment by Ghostkeeper** [comment]
We've decided to merge it anyway because even though lxml doesn't run on the CI server, we might get it working in the future (such as after the migration). The only danger is that the XSD file will get outdated if we add something to the fdm material file specification, but we accept that risk. I've added some documentation to warn against this.

**Pull request merged**
