### PR TITLE
Material PC changes

### PR DESCRIPTION
**Pull request by maukcc**

### CODE REVIEW

**Comment by maukcc** [comment]
maybe a good idea to add something like a carriage return to the description and adhesion info for a better view.

**Comment by Ghostkeeper** [comment]
Your changes seem to be coming through in Cura (using the Cartesio printer), so I'm merging them.

Are you sure your bed can reach that 135 degree temperature?

**Comment by Ghostkeeper** [comment]
Oh, and regarding the carriage return, I wouldn't do that in the data if it is for better formatting, only if it is for paragraphing. Formatting is up to the display device. The data in this repository is intended to be used by multiple systems, some of which have a very small display area.

**Comment by maukcc** [comment]
140 degrees for the bed is easy, 141 takes 30minutes :)
I will be adding our other 2 Cartesio machines as well, and then change the generic materials accordingly. I will also change the description info for all the generic materials.

**Pull request merged**
