### PR TITLE
Add substitute script along with readme

### PR DESCRIPTION
**Pull request by jackha**

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Why perl and not Python (which is something all UM developers can understand)?

**Comment by rvdh** [comment]
I would suggest using neither perl nor python for this.
Instead, this simple bash oneliner would do the same:

`for i in $(ls targetDirectory); do sed -i '/regex/replacement/' $i; done`

(on macOS add .bak after -i)

**Comment by jackha** [comment]
@robinmdh I'm assigning you as I only added the script.

**Comment by robinmdh** [comment]
I refuse to refactor something that I as only using and only mailed to a select few people as a here, this works.

The reason I use perl is because I wrote this script 15~20 years ago...
no warranty was given, use at your peril, etc!

**Comment by ChrisTerBeke** [comment]
That's fine but then I think it should't be added here as there's a very low change that it'll be widely used and maintained.

**Comment by robinmdh** [comment]
I agree, I wouldn't have made a PR for this.
I would see it as a take it as is or leave it, with the documentation it might be useful to a select few.
Though the checked-in script did not work for me, and using this was easier than figuring out why.
I wouldn't use somthing like that bash script as I don't like sed... (or awk)

This is just something left over from my history with Perl which is an awesome language for any string manipulation, is still faster than python, doesn't have a GIL, etc, even if its syntax does looks like line noise :stuck_out_tongue_closed_eyes: 

so I'll close the PR then.

**Comment by jackha** [comment]
At least it's now not only in my e-mail anymore, that's what I was aiming for

**Pull request closed without merging**
